resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

serviceMonitor:
  enabled: true
  namespace: listmonk
  interval: 30s
  labels:
    release: kps
# Credenciales
config:
  datasource:
    host: postgres.listmonk.svc.cluster.local
    port: "5432"
    sslmode: disable

    user: ""
    userSecret:
      name: postgres-secret
      key: POSTGRES_USER

    password: ""
    passwordSecret:
      name: postgres-secret
      key: POSTGRES_PASSWORD

    database: "listmonk"
