apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount-listmonk.yaml
  - serviceaccount-postgres.yaml
  - postgres-sealedsecret.yaml
  - postgres-pvc.yaml
  - postgres-deploy.yaml
  - postgres-svc.yaml
  - listmonk-uploads-pvc.yaml
  - analysistemplate-listmonk-smoke.yaml
  - listmonk-rollout.yaml
  - listmonk-svc.yaml
  - listmonk-preview-svc.yaml
  - listmonk-ingress.yaml
  - listmonk-preview-ingress.yaml
  - networkpolicy-allow-egress-from-listmonk.yaml
  - networkpolicy-allow-ingress-from-ingress-nginx-to-listmonk.yaml
  - networkpolicy-allow-ingress-from-listmonk.yaml
  - networkpolicy-allow-ingress-from-analysis-to-listmonk.yaml
  - networkpolicy-allow-egress-analysis.yaml
  - networkpolicy-allow-egress-dns.yaml
  - networkpolicy-default-deny.yaml
images:
  - name: ghcr.io/ericnovales/listmonk_ericmod
    newTag: v1.5.0

