apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listmonk-preview
  namespace: listmonk
spec:
  ingressClassName: nginx
  rules:
    - host: preview-listmonk.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: listmonk-preview
                port:
                  number: 9000
