apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-listmonk-from-analysis
  namespace: listmonk
spec:
  podSelector:
    matchLabels:
      app: listmonk
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: analysis
      ports:
        - protocol: TCP
          port: 9000
