apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount-listmonk.yaml
  - serviceaccount-postgres.yaml
  - postgres-sealedsecret.yaml
  - postgres-pvc.yaml
  - postgres-deploy.yaml
  - postgres-svc.yaml
  - listmonk-uploads-pvc.yaml
  - listmonk-deploy.yaml
  - listmonk-svc.yaml
  - listmonk-ingress.yaml

