apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - mailpit-deploy.yaml
  - mailpit-svc.yaml
  - mailpit-ingress.yaml
  - networkpolicy-allow-ingress-from-ingress-nginx.yaml
  - networkpolicy-allow-ingress-from-listmonk.yaml
  - networkpolicy-default-deny.yaml
