apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-smtp-from-listmonk
  namespace: mail
spec:
  podSelector:
    matchLabels:
      app: mailpit
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: listmonk
      ports:
        - protocol: TCP
          port: 1025
