apiVersion: v1
kind: Secret
metadata:
  name: aws-user
  namespace: listmonk
type: Opaque
stringData:
  aws-access-key-id: test         # CAMBIAR POR TU USER
  aws-secret-access-key: test   # CAMBIAR POR TU PASSWORD
