alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ["namespace", "alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 2h
      receiver: "webhook-receiver"

      routes:
        - receiver: "null"
          matchers:
            - alertname = "Watchdog"

    receivers:
      - name: "null"

      - name: "webhook-receiver"
        webhook_configs:
          - url: "http://webhook-receiver.monitoring.svc.cluster.local:8080"
            send_resolved: true
