apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-pvc.yaml
  - postgres-deploy.yaml
  - postgres-svc.yaml
  - listmonk-uploads-pvc.yaml
  - analysistemplate-listmonk-smoke.yaml
  - listmonk-rollout.yaml
  - listmonk-svc.yaml
  - listmonk-preview-svc.yaml
  - listmonk-ingress.yaml
  - listmonk-preview-ingress.yaml
  - postgres-backup-cronjob.yaml
images:
  - name: ghcr.io/ericnovales/listmonk_ericmod
    newTag: v1.6.0

