apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: listmonk
type: Opaque
stringData:
  POSTGRES_DB: listmonk #CAMBIAR POR TU DB
  POSTGRES_USER: listmonk #CAMBIAR POR TU USER
  POSTGRES_PASSWORD: listmonk #CAMBIAR POR TU PASSWORD
